
negatives = [
  "END OF E",
  "THE EN",
  "Descartes",
  "scooter",
  "Nevada",
  "Output:",
  "Note:",
  "### Note",
  "## Answer",
  "Answer:",
  "Please output all of the triples from the text",
  "Reference:",
  "<|im_sep|",
  "Note that we have ignored the use of proper nouns in the text as they are not relevant to the task of extracting knowledge triples",
  "Please explain your solution and why it works",
  "EXAM",
  "SORRY IF I MISSED ANY KNOWLEDGE TRIPLES - PLEASE CONFIRM",
  "This text should be processed to extract knowledge triples from it",
  "Please note that we are also trying to understand the relationships between these entities",
  "The knowledge triples represent information being passed through a networked intelligence agent",
  "Please keep in mind that this is a very difficult problem. It requires understanding natural language",
  "knowledge triples can be extracted from a tex",
  "Reference(s)",
  "after all of you had left",
  "This is the text you have to extract the knowledge triples from",
  "Please provide me with a sample text to analyze",
  "NOTE",
  "there are no knowledge triples",
  "The knowledge triples output for the provided text are",
  "Input: The game of thrones",
  "Answer for the knowledge triples output"
]
 
